# Generated by Django 4.2.2 on 2023-06-24 06:28

from django.db import migrations, models
import validators.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[validators.validators.first_name_length_char_validator, validators.validators.name_start_with_letter_validator])),
                ('last_name', models.CharField(max_length=25, validators=[validators.validators.last_name_length_char_validator, validators.validators.name_start_with_letter_validator])),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(validators=[validators.validators.password_length_validator])),
                ('image', models.URLField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, default=18, null=True)),
            ],
        ),
    ]
