# Generated by Django 4.2.2 on 2023-06-24 07:26

from django.db import migrations, models
import validators.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(validators=[validators.validators.fruit_name_validator, validators.validators.fruit_name_contain_only_letters_validator])),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('nutrition', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
